# Generated by Django 6.0.4 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('divisionalid', models.AutoField(primary_key=True, serialize=False)),
                ('Divisionname', models.CharField(max_length=255)),
                ('zoneID', models.IntegerField()),
            ],
            options={
                'db_table': 'Division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('UnitID', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpDOB', models.DateField(blank=True, null=True)),
                ('StaffTypeID', models.IntegerField(blank=True, null=True)),
                ('DesigID', models.IntegerField(blank=True, null=True)),
                ('DeptID', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('DOR', models.DateField(blank=True, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EmployeeMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionAllotment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staffid', models.IntegerField(blank=True, null=True)),
                ('regionid', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regionAllotment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionMaster',
            fields=[
                ('regionid', models.AutoField(primary_key=True, serialize=False)),
                ('regionname', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'regionmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='signUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('empId', models.IntegerField()),
            ],
            options={
                'db_table': 'signUP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SonataUsersKYCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StageID', models.IntegerField()),
                ('EmpID', models.BigIntegerField(unique=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('MobileNo', models.CharField(max_length=15)),
                ('AdhaarNo', models.CharField(max_length=12)),
                ('PAN_Number', models.CharField(max_length=10)),
                ('AdhaarFrontImg', models.BinaryField(blank=True, max_length='max', null=True)),
                ('AdhaarBackImg', models.BinaryField(blank=True, max_length='max', null=True)),
                ('PAN_Img', models.BinaryField(blank=True, max_length='max', null=True)),
                ('DL_Img', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Passbook_Img', models.BinaryField(blank=True, max_length='max', null=True)),
                ('RecievedDate', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsProcessed', models.IntegerField(default=0)),
                ('FinalVerified_by', models.IntegerField(blank=True, null=True)),
                ('Verified_Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tbl_Sonata_Users_KYC_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SonataUsersKYCTransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefID', models.IntegerField(blank=True, null=True)),
                ('EmpID', models.IntegerField(blank=True, null=True)),
                ('StageID', models.IntegerField(blank=True, null=True)),
                ('IsVerified', models.IntegerField(blank=True, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Stage', models.IntegerField(blank=True, null=True)),
                ('Verified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tbl_Sonata_Users_KYC_Transaction_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSonataUsersKYCDataSignDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField(blank=True, null=True)),
                ('FullName', models.CharField(max_length=255)),
                ('AadharNo', models.CharField(max_length=12, unique=True)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PO', models.CharField(blank=True, max_length=255, null=True)),
                ('Loc', models.CharField(blank=True, max_length=255, null=True)),
                ('Vtc', models.CharField(blank=True, max_length=255, null=True)),
                ('Street', models.CharField(blank=True, max_length=255, null=True)),
                ('House', models.CharField(blank=True, max_length=255, null=True)),
                ('Landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('ZIP', models.CharField(max_length=10)),
                ('ProfileImage', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Care_Of', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.TextField(blank=True, null=True)),
                ('uniqueness_id', models.TextField(blank=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tbl_Sonata_Users_KYC_Data_SignDesk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('unitid', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=255)),
                ('districtid', models.IntegerField(blank=True, null=True)),
                ('regionid', models.IntegerField(blank=True, null=True)),
                ('stateid', models.IntegerField(blank=True, null=True)),
                ('esiapplicable', models.BooleanField(default=False)),
                ('statename', models.CharField(blank=True, max_length=255, null=True)),
                ('isopen', models.BooleanField(default=False)),
                ('currentaddress', models.TextField(blank=True, null=True)),
                ('workingstatus', models.BooleanField(default=True)),
                ('dateofopening', models.DateField(blank=True, null=True)),
                ('applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('registrationno', models.CharField(blank=True, max_length=255, null=True)),
                ('renewaldate', models.DateField(blank=True, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('docstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('filelink', models.URLField(blank=True, null=True)),
                ('cmbdocumenttype', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_unit_id', models.IntegerField(blank=True, null=True)),
                ('hubid', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('officetypeid', models.IntegerField(blank=True, null=True)),
                ('reportingunitid', models.IntegerField(blank=True, null=True)),
                ('misname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'unitmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HR_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('blocked_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'loginstatus',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='retest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='section',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='section_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('employee_id', 'section')},
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='Quiz_Employee',
        ),
        migrations.AlterModelTable(
            name='quizresult',
            table='candidate_assessments_result',
        ),
    ]
